name: Build & Deploy to docs/

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build into docs/
        run: npm run build
        # (build.outDir === 'docs' in your vite.config.js)

      - name: Commit & push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m "ci: deploy docs [skip ci]" || echo "No changes to deploy"
          git push origin main
