# .github/workflows/deploy.yml
name: Build & Deploy to docs/

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout and keep credentials so we can push back
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install deps & build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # 4) Copy `dist/` into `docs/` and commit it
      - name: Deploy to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -R dist/* docs/
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m "ci: deploy to docs/ [skip ci]" || echo "Nothing to commit"
          git push origin main
